version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      npm-dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      npm-major-dev-dependencies:
        dependency-type: 'development'
        update-types:
          - 'major'
      npm-production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'minor'
          - 'patch'
      npm-major-production-dependencies:
        dependency-type: 'production'
        update-types:
          - 'major'
