name: Build

on: [pull_request]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check commit message type
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '^(feat|fix|docs|style|refactor|test|chore).+'
          error: 'Commit messages must begin with a valid commit type.'
          excludeDescription: 'true'
          excludeTitle: 'true'
          checkAllCommitMessages: 'true'
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install npm dependencies
        run: npm ci
      - name: Persist workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: .
          retention-days: 1

  lint-and-test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Use workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace
      - name: Run linters
        run: npm run lint
