name: Monitor

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  check-accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: install npm dependencies
        run: npm ci
      - name: run html linter
        run: npm run lint:html
